### ISSUE TITLE
X-Mailgun-Variables do not get passed to webhooks

### ISSUE THREAD

**Issue by vinceprofeta** [orliesaurus/nodemailer-mailgun-transport#70]
It looks like X-Mailgun-Variables are not in the white list to get sent to Mailgun. Can this get updated?

**Comment by orliesaurus** [comment]
Merged

**Comment by vinceprofeta** [comment]
@orliesaurus I built a version from my fork and this still does not come though the web hook? Do you have any ideas for why tags nor X-Mailgun-Variables come through the webhook?

**Comment by daviduffy** [comment]
I was struggling with this as well. It turns out you can add variables and have them appear in the 'user-variables' hash if you set up your mail options like this:

```javascript
...
    from: `${fromName} <${fromEmail}>`,
    to,
    subject,
    html,
    'v:custom': JSON.stringify({ someKey: 'someValue' })  // custom var, prefix with 'v:'
...
```

I needed to pass a value through a webhook POST in order to attribute it to the correct entry in my DB, and the output from the webhook passed this custom var through perfectly:

```
...
2018-12-13T05:26:46.726891+00:00 app[web.1]:      reason: 'generic',
2018-12-13T05:26:46.726893+00:00 app[web.1]:      'user-variables': { custom: '{"someKey":"someValue"}' },
2018-12-13T05:26:46.726895+00:00 app[web.1]:      flags: 
...
```

**Comment by framp** [comment]
X-Mailgun-Variables are now being passed to mailgun /cc @orliesaurus
